### ISSUE TITLE
Double letters, when there aren't any

### ISSUE THREAD

**Issue by Manticore-007** [ltsSmitty/swordle#1]
![image](https://github.com/ltsSmitty/swordle/assets/71702374/c9b31ff2-2d16-40fe-8f4f-8e848f5213bd)

A letter that's already guessed still turns yellow, while there isn't a second one. In the example the "D" is already guessed at the correct place (green). But the other "D" turns yellow while there isn't a second "D". The word was GUARD by the way.

I'm not sure if you are going to fix it, I just played the game and want to let you know ;-)

**Comment by ltsSmitty** [comment]
Hey thanks for looking at this! I fixed this behavior in my my most recent commit. Can you see if it plays again as you expect?
